/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AxBubble: typeof import('@antdv-next/x')['Bubble']
    AxProvider: typeof import('@antdv-next/x')['XProvider']
    AxSender: typeof import('@antdv-next/x')['Sender']
    AxWelcome: typeof import('@antdv-next/x')['Welcome']
  }
}
